
DROP DATABASE dyngroups;
CREATE DATABASE dyngroups;
use dyngroups;

CREATE TABLE DYN_ATTRIBUTES (
  ATT_ID int(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  ATT_NAME  VARCHAR(50) UNIQUE NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE DYN_GROUPS (
  GRP_ID int(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  GRP_NAME VARCHAR(250) UNIQUE NOT NULL,
  GRP_DEF VARCHAR(250) NOT NULL,
  GRP_ATT_NB int(10)) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE DYN_ATTRIBUTE_VALUES (
  ATTVAL_ID int(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  ATT_ID int(10) NOT NULL,
  ATTVAL_VALUE  VARCHAR(100) NOT NULL,
  ATTVAL_NEGATIVE  BOOLEAN NOT NULL,
  GRP_ID int(10) NOT NULL,
 CONSTRAINT `FK_ATT_ID` FOREIGN KEY (`ATT_ID`) REFERENCES `DYN_ATTRIBUTES` (`ATT_ID`) ON UPDATE CASCADE ON DELETE RESTRICT ,
 CONSTRAINT `FK_GRP_ID` FOREIGN KEY (`GRP_ID`) REFERENCES `DYN_GROUPS` (`GRP_ID`) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

